In [6]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
a =np.matrix([[1,2]]).T
b = np.matrix([[3,4,5,6,7,8]]).reshape((2,3))
a
b
np.array(a)*np.array(b)

matrix([[1],
        [2]])

matrix([[3, 4, 5],
        [6, 7, 8]])

array([[ 3,  4,  5],
       [12, 14, 16]])